### PR TITLE
migrate to Yazi Lua API v4.0

### PR DESCRIPTION
**Pull request by smangels**

### CODE REVIEW

**Comment by smangels** [comment]
tested with Yazi version 0.4.2

**Comment by lmBored** [comment]
scrolling in the preview panel in yazi is not possible with this change.

**Comment by smangels** [comment]
You were right, scrolling was not possible. I've took the code for a SEEK function from another plugin and got it to work.

**Comment by lmBored** [comment]
You can also use the latest version of main repo, there's an accepted PR that fixed the scrolling issue, and added some features like scroll with hotkey.

**Pull request closed without merging**
